source 'https://rubygems.org'

gem 'jekyll', '~> 3.10'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-redirect-from'
gem 'jekyll-seo-tag'
gem 'jekyll-optional-front-matter'
gem 'jekyll-readme-index'
gem 'jekyll-default-layout'
gem 'jekyll-titles-from-headings'
gem 'jekyll-relative-links'
gem 'webrick', '~> 1.8'
